### ISSUE TITLE
Login not working for mixins

### ISSUE THREAD

**Issue by squidnugget07** [bytespacegames/MCPClientBrowserAuth#3]
i tried using this code with mixins however its not working, is only mcp supported and mixins dont work with this? i tried it with mcp a couple months ago and it worked just fine, what am i doing wrong (veerything works fine until it says attemted to login to minecraft, i go into a singleplayuer world and test it out and it dosent work, below is my error code ) 

java.lang.NullPointerException
	at com.quiap.Vexcty.client.account.SessionUtils.recieveResponse(SessionUtils.java:92)
	at com.quiap.Vexcty.client.account.ws.WebServer$MyHandler.handle(WebServer.java:74)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)

this is line 92 in SessionUtils 
String name = loginProfileInfo.getString("name");

and line 74 in WebServer
SessionUtils.recieveResponse(code);

please help ,
thanks

**Comment by notpoiu** [comment]
this code was only tested for mcp, not for mixins however we may support mixins at a future date

**Comment by notpoiu** [comment]
in the meantime you may use openauth as it has a webview login however it did not work for mcp 1.8.8

**Comment by squidnugget07** [comment]
when i tested mcp 1.8.8 it worked perfectly fine but with mixins it didnt work, do you know a date or roughly when you will add support for mixins?

**Comment by spacebytee** [comment]
> when i tested mcp 1.8.8 it worked perfectly fine but with mixins it didnt work, do you know a date or roughly when you will add support for mixins?

The client we made this for is being rewritten in its entirety for Legacy Fabric, so probably soon.
